= Deterministically Dynamic Storage Allocation
ifndef::compositing[]
:author: cyotee doge
:email: cyotee@syscoin.org
:revdate: 2022-02-19
:revnumber: 0.1
:revremark: Initial draft.
:toc:
:toclevels: 6
:sectnums:
:data-uri:
:stem: asciimath
:pathtoroot: ../../
:imagesdir: {pathtoroot}
:includeprefix: {pathtoroot}
:compositing:
endif::[]

Deterministically Dynamic Storage Allocation (DDSA) takes advantage of built-in hashing functionality of the EVM.
By enforcing the implementation of all datatypes as libraries defining custom structs, a consistent bytecode for that datatype is defined.
And example can be seen the following code sample.

[source, solidity]
----
library String {

  struct Layout {
    string value;
  }

  function _layout( bytes32 slot ) pure internal returns ( String.Layout storage layout ) {
    assembly{ layout.slot := slot }
  }

}
----

The datatype libraries for the ASE are implemented as a struct containing just the desired primitive datatype.
Each datatype library also implements the a standard function used to bind a storage pointer to an instance of the struct.
The name of the library must be the same as, or directly descriptive of, the primitive datatype.
This provides a standardized implementation that results in consistent bytecode.

A utility library is implemented to facilitate use of the datatype library.
An example can be seen here.

[source, solidity]
----
library StringUtils {

  bytes32 constant internal STRUCT_STORAGE_SLOT = keccak256(type(String).creationCode);

  function _structSlot() pure internal returns (bytes32 structSlot) {
    structSlot = STRUCT_STORAGE_SLOT;
  }

  function _layout( bytes32 slot ) pure internal returns ( String.Layout storage layout ) {
    layout = String._layout(slot);
  }

}
----

A constant is calculated by hashing the bytecode of the library defining the datatype struct.
This is made available with the standard `_structSlot()` function.
The standardization of the struct library implementations, and the hashing of that bytecode ensures that the correct struct is being used to access storage.
A reimplementation of the `_layout(bytes32)` function is also provided to facilitate reuse of this library.
This way code that includes this library does not have to tightly couple their implementations for the underlying datatype library.
While Solidity does not have full polymorphism, this process allows us to leverage the pseudo-polymorphism that's available.

The usage of bytecode hashes as storage slots is the foundation of the storage standard used in the ASE.
From here, a modification of the Diamond Storage design pattern is applied.

In th Diamond Storage design pattern, the state variables for a particular implementation is composed into one or more structs.
The storage slot is also defined using a hash of some value.
The design pattern has no opinion on the values to hash.
While this is appropriate for a design pattern, the ASE framework asserts an opinion.

One of the common problems with applying Diamond Storage is the complexities around using dynamic length datatypes.
While storage slot packing can be used, this also introduces a potential conflict.
An update to a facet applying Diamond Storage may introduce an incompatibility with how the storage has been managed until the update is applied.
The ASE applies Diamond Storage to the base datatype library usage.
And example can be seen below.

[source,solidity]
----
include::../../../contracts/types/primitives/String.sol[]
----

This process of wrapping the datatype libraries in a domain specific struct it forces dynamic length dataypes into storage pointers.
Further, the standard `_layout(bytes32)` function combines the default storage slot for each of the composed datatypes.
This helps ensure that the structure for a set of state variables is consistently stored based on that structure.
This way, in the event of a failure to implement the libraries to access the storage previously unused storage is accessed.
This helps protect existing data.
A parameter is available to provide a salt to group usage of a struct by the exposed smart-contract interface.

So far this has covered how storage is managed internally.
But state variables exists in service of implementing an interface.
This why the usage of datatype structs with Diamond Storage within the ASE is bound to the interfaces exposed by particular facets.
And example of this can be seen below.

[source,solidity]
----
abstract contract MessengerInternal {

  using MessengerLib for MessengerStorage.Layout;

  function _setMessage(
    string memory message
  ) internal {
    MessengerLib._layout(type(IMessenger).interfaceId)
      ._setMessage(message);
  }

  function _getMessage() view internal returns (string memory message) {
    message = MessengerLib._layout(type(IMessenger).interfaceId)
      ._getMessage();
  }
  
}
----

This example is of an abstract contract that implements the desired domain logic.
The domain logic uses the interface ID this is to serve as the salt for the storage slot calculation.
This allows for two main features.

First, the usage is a Diamond Storage struct can be grouped by the interface ID that struct supports.
This allows for safely reusing Diamond Storage structs in other facets to support other interfaces.
Because the Diamond Storage struct is using a deterministic storage slot computed from its structure, it can be reliably allocated to a range of storage slots.
And the complex datatypes that consume a dynamic amount of storage are deterministically distributed to other storage slots based on the base storage slot.
This greatly minimizes the chance of storage slot collisions across facets, while promoting code reuse.

Second, this allows for facets to reliably interact with storage across interfaces by having a reliable process for calculating the storage slots used in service of that interface.
This way the functionality and flexibility of a proxy is greatly enhanced due to the consistent storage allocations.
And remains consistently safe.
While the chance for storage slot collisions typically goes up as more Diamond Storage structs are used; the cascading distribution of slots distributes the chance across an ever greater range.
This is akin to the solution for the Infinite Hotel Paradox.
By including the set of possible values in the distribution formula for that set of values, you get an ever expanding variance in the distribution.
A simple diagram explaining this is below.

image::images/architecture/daosys-architecture-01-ase-01-storage-01-deterministically_dynamic_storage_allocation.drawio.svg[align=center]

The storage slots for the discrete data types are combined using a bitwise XOR operation.
This does abstract out the exact order of the datatypes in the Diamond Storage struct.
This is abstraction is intentional as it should catch an unsafe ordering of state variables during testing.
A possible improvement is to use an order dependent bitwise operation.
This will need further research.
Then to group the Diamond Storage structs by the interface they serve, the interface ID is applied using bitwise XOR.
This results in a consistent prefix for all the storage slots used by an interface.
Overall, this replicates a primary to foreign key relationship for calculating the storage slots used by a facet.
This allows for using the EVM storage solution like a relational database.
Together, this allows for a on-chain factory that can deploy proxy and initialize them any combination of facets without encountering a storage slot collision for an any arbitrary set of facets.