= Transaction Router Design Pattern
ifndef::compositing[]
:author: cyotee doge
:email: cyotee@syscoin.org
:revdate: 2022-02-19
:revnumber: 0.1
:revremark: Initial draft.
:toc:
:toclevels: 6
:sectnums:
:data-uri:
:stem: asciimath
:pathtoroot: ../../
:imagesdir: {pathtoroot}
:includeprefix: {pathtoroot}
:compositing:
endif::[]

The Transaction Router design pattern is used when simple function selector based logic delegation does not fully serve a use case.
A Transaction Router infers the desired operation from the transaction context.
In this case, the transaction context is the implicit variables and explicit arguments sent by the user to execute a transaction.
The logic inference is typically domain specific.

An example of a Transaction Router can be defined based on ERC-20.
In this example, the ERC-20 token is a liquidity pool (LP) token.
The LP token takes deposits from users, and mints a balance to the user to represent their deposit.

Typically LP tokens will expose a domain specific interface to handle deposits.
This may be needed in some domains.
But in many domains, it is possible to infer the desire to deposit and withdraw from the transaction context.
For example, if a user issues a transaction that defines transferring some of the LP tokens from the token contract to themselves, we can infer that the user wishes to make a deposit.

A user would do this by calling the `transferFrom(address holder, address recipient, uint256 amount)` function.
They would provide the token address as the `holder` parameter and themselves as the `recipient` parameter.
The LP can reasonably infer that because the user does not have the authority to transfer any of the token's balance of itself, obviously they wish to make a deposit.
Thus, the LP token would use a Transaction Router Delegate Service to determine which Delegate Service to use to process the transaction.