= Autonomous Service Engine Architecture
:author: cyotee doge
:email: cyotee@syscoin.org
:revdate: 2022-02-19
:revnumber: 0.1
:revremark: Initial draft.
:toc:
:toclevels: 6
:sectnums:
:data-uri:
:stem: asciimath

ifndef::compositing[]
:imagesdir: ../../
endif::[]

ifndef::compositing[]
:compositing:
endif::[]

== Introduction

The Autonomous Service Engine (ASE) is a proxy factory.
The architecture merges the Diamond Proxy and Factory design patterns.
Users may have the factory deploy a proxy configured with the functionality they wish.
This allows users to compose a variety of functionality in a single proxy.

== Design Patterns

=== Factory Design Pattern

The Factory design pattern utilizes the CREATE and CREATE2 OPCODES of the EVM to deploy new smart contracts.
A typical factory will deploy initialize a single type of smart-contract.
An example of this can be seen in any AMM, such as Balancer and Uniswap.
The CREATE2 OPCODE allows for salting the smart-contract address calculation to make it computable.
Factories will typically use this functionality to deploy contracts to addresses that can be precomputed.
This allows for smart-contract address discovery without having to read from storage.

A unutilized second order feature is available by using CREATE2 to deploy contracts from a factory.
Because addresses can be precomputed, they can also be verified through recomputation.
When deploying a smart-contract from another smart-contract, a hash of the factory's bytecode is used to calculate the address of the new smart-contract.
This bytecode is available on-chain from the smart-contract address, and is therefore immutable.
This means that when a smart-contract is deployed, it can self-report it's factory and salt used when it was deployed.
A smart-contract can verify the pedigree of a contract by recalculating the contract address.
This means that an implicit trust can be bootstrapped from an address.

This pedigree verification capability is used by the ASE to allow for an implicit access control list (ACL).
The implicit ACL can be used by modules available from the ASE to allow integration with new proxies deployed by the factory.
Proxies can allow interaction with tokens and pools that have not been deployed yet.

=== Proxy Design Pattern

The Proxy design pattern utilizes the DELEGATECALL OPCODE of the EVM to reuse another smart-contract's logic.
A proxy is implemented to use DELEGATECALL for most of it's functionality.
This is done by deploying a small contract that uses DELEGATECALL to the contract that implements it's logic for any undefined functions.
There are several standards that define how a proxy can be configured ot updated to use a particular implementation.
The ASE defines it's own optimized standard.
This optimized standard combines the Minimal Proxy reference implementation with a slimmer version of the Diamond reference implementation.

=== Diamond Design Pattern

The Diamond design pattern defines how a proxy can delegate to several smart-contracts.
This is done with an implementation that maps a function selector to an address that implements that function.
The target address for this mapping is typically called a Facet.
This allows for a single address to expose far more functionality then can typically be implemented in a single smart-contract.
This also allows for partial modifications to the proxies functionality by changing the configuration to direct to a new facet.
Unfortunately, post-deployment updates can not be secured against potential malicious action.
Additionally, the manner by which the EVM manages the data stored for a smart-contract complicates composing several facets into a diamond proxy.

There is no way to secure an updatable diamond proxy against a potentially malicious update of one of its facets.
The ASE only uses the Diamond design pattern to deploy new proxies.
Once deployed, these proxies may not be updated.

A common problem with using proxies, especially diamond proxies, is how the EVM stores a smart-contract's data, or state.
The EVM stores data in a single column table consisting of 32 byte words.
The rows in this column are called slots.
Slots are 0 indexed and iterate consecutively to 2^256
If data to be stored is too large or too complex to store in 32 bytes, the data stored is the the index of another slot.
The the data is stored by starting with the indexed slot, and using each consecutive slot until the full data is stored.
The Solidity and Vyper compilers both assign the storage slot to be used automatically.
The storage slot indexes are termed, storage pointers.

While it is possible to use Assembly to directly access specific slots, this is a fragile process.
When dealing with dynamically sized datatypes, like strings and arrays, direct storage access using Assembly must know the size of the data.
Fortunately, Assembly does simplify this process by exposing an implicit variable for all storage datatypes that defines the storage pointer for that variable.

The ASE solves this complexity with a new storage standard.
By making minimal use of in-line Assembly with Solidity a consistently calculated storage slot index may be set to the storage slot implicit variable of a storage variable.
This is most easily done with custom datatypes defined as Structs.
This process of setting the storage slot for a storage variable of a custom Struct is termed, binding.
As in, "The struct that stores the user's balances is bound to slot index 0".
The ASE defines a design standard for implementing all datatypes as structs so that they may be dynamically bound to storage slots.

== Design Standards

=== Deterministically Dynamic Storage Allocation

Deterministically Dynamic Storage Allocation (DDSA) takes advantage of built-in hashing functionality of the EVM.
By enforcing the implementation of all datatypes as libraries defining custom structs, a consistent bytecode for that datatype is defined.
And example can be seen the following code sample.

[source, solidity]
----
library String {

  struct Layout {
    string value;
  }

  function _layout( bytes32 slot ) pure internal returns ( String.Layout storage layout ) {
    assembly{ layout.slot := slot }
  }

}
----

The datatype libraries for the ASE are implemented as a struct containing just the desired primitive datatype.
Each datatype library also implements the a standard function used to bind a storage pointer to an instance of the struct.
The name of the library must be the same as, or directly descriptive of, the primitive datatype.
This provides a standardized implementation that results in consistent bytecode.

A utility library is implemented to facilitate use of the datatype library.
An example can be seen here.

[source, solidity]
----
library StringUtils {

  bytes32 constant internal STRUCT_STORAGE_SLOT = keccak256(type(String).creationCode);

  function _structSlot() pure internal returns (bytes32 structSlot) {
    structSlot = STRUCT_STORAGE_SLOT;
  }

  function _layout( bytes32 slot ) pure internal returns ( String.Layout storage layout ) {
    layout = String._layout(slot);
  }

}
----

A constant is calculated by hashing the bytecode of the library defining the datatype struct.
This is made available with the standard `_structSlot()` function.
The standardization of the struct library implementations, and the hashing of that bytecode ensures that the correct struct is being used to access storage.
A reimplementation of the `_layout(bytes32)` function is also provided to facilitate reuse of this library.
This way code that includes this library does not have to tightly couple their implementations for the underlying datatype library.
While Solidity does not have full polymorphism, this process allows us to leverage the pseudo-polymorphism that's available.

The usage of bytecode hashes as storage slots is the foundation of the storage standard used in the ASE.
From here, a modification of the Diamond Storage design pattern is applied.

In th Diamond Storage design pattern, the state variables for a particular implementation is composed into one or more structs.
The storage slot is also defined using a hash of some value.
The design pattern has no opinion on the values to hash.
While this is appropriate for a design pattern, the ASE framework asserts an opinion.

One of the common problems with applying Diamond Storage is the complexities around using dynamic length datatypes.
While storage slot packing can be used, this also introduces a potential conflict.
An update to a facet applying Diamond Storage may introduce an incompatibility with how the storage has been managed until the update is applied.
The ASE applies Diamond Storage to the base datatype library usage.
And example can be seen below.

[source,solidity]
----
library MessengerStorage {

  struct Layout {
    String.Layout message;
  }

  function _layout(bytes32 salt) pure internal returns (MessengerStorage.Layout storage layout) {
    bytes32 saltedSlot = salt ^ StringUtils._structSlot();
    assembly{ layout.slot := saltedSlot }
  }
  
}
----

This process of wrapping the datatype libraries in a domain specific struct it forces dynamic length dataypes into storage pointers.
Further, the standard `_layout(bytes32)` function combines the default storage slot for each of the composed datatypes.
This helps ensure that the structure for a set of state variables is consistently stored based on that structure.
This way, in the event of a failure to implement the libraries to access the storage previously unused storage is accessed.
This helps protect existing data.
A parameter is available to provide a salt to group usage of a struct by the exposed smart-contract interface.

So far this has covered how storage is managed internally.
But state variables exists in service of implementing an interface.
This why the usage of datatype structs with Diamond Storage within the ASE is bound to the interfaces exposed by particular facets.
And example of this can be seen below.

[source,solidity]
----
abstract contract MessengerInternal {

  using MessengerLib for MessengerStorage.Layout;

  function _setMessage(
    string memory message
  ) internal {
    MessengerLib._layout(type(IMessenger).interfaceId)
      ._setMessage(message);
  }

  function _getMessage() view internal returns (string memory message) {
    message = MessengerLib._layout(type(IMessenger).interfaceId)
      ._getMessage();
  }
  
}
----

This example is of an abstract contract that implements the desired domain logic.
The domain logic uses the interface ID this is to serve as the salt for the storage slot calculation.
This allows for two main features.

First, the usage is a Diamond Storage struct can be grouped by the interface ID that struct supports.
This allows for safely reusing Diamond Storage structs in other facets to support other interfaces.
Because the Diamond Storage struct is using a deterministic storage slot computed from its structure, it can be reliably allocated to a range of storage slots.
And the complex datatypes that consume a dynamic amount of storage are deterministically distributed to other storage slots based on the base storage slot.
This greatly minimizes the chance of storage slot collisions across facets, while promoting code reuse.

Second, this allows for facets to reliably interact with storage across interfaces by having a reliable process for calculating the storage slots used in service of that interface.
This way the functionality and flexibility of a proxy is greatly enhanced due to the consistent storage allocations.
And remains consistently safe.
While the chance for storage slot collisions typically goes up as more Diamond Storage structs are used; the cascading distribution of slots distributes the chance across an ever greater range.
This is akin to the solution for the Infinite Hotel Paradox.
By including the set of possible values in the distribution formula for that set of values, you get an ever expanding variance in the distribution.
A simple diagram explaining this is below.

image::images/architecture/daosys-architecture-01-ase-01-storage-01-deterministically_dynamic_storage_allocation.drawio.svg[align=center]

The storage slots for the discrete data types are combined using a bitwise XOR operation.
This does abstract out the exact order of the datatypes in the Diamond Storage struct.
This is abstraction is intentional as it should catch an unsafe ordering of state variables during testing.
A possible improvement is to use an order dependent bitwise operation.
This will need further research.
Then to group the Diamond Storage structs by the interface they serve, the interface ID is applied using bitwise XOR.
This results in a consistent prefix for all the storage slots used by an interface.
Overall, this replicates a primary to foreign key relationship for calculating the storage slots used by a facet.
This allows for using the EVM storage solution like a relational database.
Together, this allows for a on-chain factory that can deploy proxy and initialize them any combination of facets without encountering a storage slot collision for an any arbitrary set of facets.

== Architecture

The Autonomous Service Engine uses a on-chain factory to deploy minimal proxies of a customized Diamond Proxy that is configured with facets as defined by the user.
Because of the customization that deviates sharply from the Diamond standard as defined in https://eips.ethereum.org/EIPS/eip-2535[ERC-2535] the defining terms are changed.
Under the ASE framework, the customized Diamond proxies are termed Service Proxies.
The Facets defined in https://eips.ethereum.org/EIPS/eip-2535[ERC-2535] are termed Services.

The distinction is in two factors.
Service Proxies are immutable.
The functions defined in https://eips.ethereum.org/EIPS/eip-2535[ERC-2535] to reconfigure a proxy to use new facets is not available by default in a Service Proxy.
This is done because there is not acceptable solution to the risk updates present to users of the proxy.
A Service Proxy may be configured with a Service that exposes a https://eips.ethereum.org/EIPS/eip-2535[ERC-2535] compliant interface for private instances.
The ASE will only deploy reconfiguration Services for a Service Proxy that includes an explicit ACL Service.

Second, Service Proxies are wrapped in a Minimal Proxy as defined in https://eips.ethereum.org/EIPS/eip-1167[ERC-1167].
The Service Proxy logic is itself a Service.
The Service Proxy Factory uses https://eips.ethereum.org/EIPS/eip-1167[ERC-1167] to deploy a Minimal Proxy that directs to the Service Proxy logic.
This minimizes the transaction fee for deploying new proxies with a minimal increase in per-transaction fees for use.
This also allows easier verification that a new Service Proxy is reusing proven code.
Finally, for particularly sensitive Services, a circuit breaker can be included to protect all Service Proxies consuming that service.
For this reason, Services will implemented to be as minimal as possible.
With emergency withdrawal or liquidation services graceful degradation for if a service is disabled.

=== Services

Services replace the Facets defined in https://eips.ethereum.org/EIPS/eip-2535[ERC-2535].
Services define a strict storage allocation and access standard beyond the theory presented in https://eips.ethereum.org/EIPS/eip-2535[ERC-2535].
A Service is a smart-contract or library implemented following the Deterministically Dynamic Storage Allocation standard.
A Service also reports the factory that deployed that contract and the salt used during deployment.
This way the recalculation of the address from the factory init code hash and salt can be used to verify new Services as an implicit ACL.

This means that the deployment process for new Services deviates from industry standard.
New Services are deployed as compiled bytecode passed to the Service Proxy Factory as the argument for the deployment function.
The Service Proxy Factory then instantiates that bytecode as a new contract.
ASE compliant Services must include the ASEServiceBootstrapper library to retrieve the address salt to initialize the Service.
This should be done by delegating to the canonical external library deployment.
ASE compliant external libraries may precalculate their address salt and store it as a constant.
The standard Service initialization functions must still be implemented, but may hard code the values and return values since they can not store state.

All Services are required to implement https://eips.ethereum.org/EIPS/eip-165[ERC-165] including the Service extension that enumerates the functions.
The Service extension to https://eips.ethereum.org/EIPS/eip-165[ERC-165] includes a per interface enumeration of the function selectors that define the interface ID.
Additionally, there is an enumeration of all the function selectors across all interface IDs, and a ServiceDef struct that includes the information for initializing a Service Proxy to consume the Service.

=== Service Registry

Services are published through the ASE's Service Registry.
When a new Service is deployed through the Service Proxy Factory, the Service Registry is updated with information about the new Service.
This includes mapping the new Service address to the bitwise XOR of the interfaces the Service exposes.
This defines the Service ID that is used to define the Service Proxy configuration used to deploy new Service Proxies.
Including any declared Service dependencies for the new service.
In addition to the custom interface, the Service Registry also implements the https://eips.ethereum.org/EIPS/eip-1820[ERC-1820] Standard as best as possible.
The deviation from ERC-1820 is documented in it's own section.

The foundation for identifying and consuming Services is the interface ID as computed by the Solidity compiler.
This is explained in https://eips.ethereum.org/EIPS/eip-165[ERC-165].
The ASE relies on https://eips.ethereum.org/EIPS/eip-165[ERC-165] interface IDs because of the computation from the bytecode.
This eliminates potential conflicts from the arbitrary naming convention proposed in https://eips.ethereum.org/EIPS/eip-1820[ERC-1820].

In the context of the Service Registry, the limitation of not being able to include duplicate Services for an interface ID is intended.
This can forces the inclusion of distinct identifiers is a duplicate is required.
And facilitates reuse of external Services with internal Services.
Services should include their own interface that extends an existing on if they tightly couple an external interface with domain specific logic.
And example would be the token standard in https://eips.ethereum.org/EIPS/eip-20[ERC-20] and how it does not dictate the internal behavior.
This has allowed for a wide variety of token logic that still conforms with the standard.
To handle deploying multiple Services that all expose the https://eips.ethereum.org/EIPS/eip-20[ERC-20] interface, new Services should extend the interface with domain specific interfaces.

A concrete example would be a Basic https://eips.ethereum.org/EIPS/eip-20[ERC-20] token compared to a rebasing https://eips.ethereum.org/EIPS/eip-20[ERC-20] token.
A rebasing token would differentiate itself with one or more interface extensions that exposes functions specific to the rebasing implementation.
This also applies to Services that compose existing Services in novel configurations.
They can distinguish themselves from the base Service by defining an interface that composes all the exposed interfaces.
If a new Service links to an external library it only needs to include external library functions as an interface extension if they will be directly mapped in the Service Proxy when configuring the service.

The Service Registry exposes the stored mapping of a Service ID to the Service Address.
While this is also computable as the Service ID is the salt for deploying a new Service, it's included for completeness with the other Service metadata.
The Service Registry also exposes the mapping of Services that serve a distinct interface.
This results in a rather large array of addresses that is not feasible to read on-chain.
This is provided for off-chain resources to provide a simple reference of all available Services for an interface ID.
Further, an enumeration of the functions declared in an interface is presented to facilitate off-chain resources searching the Service Registry.

=== Service Proxy 

The Service Proxy is a special Service that is the target of the Minimal Proxies deployed by the Factory.
It is published in the Service Registry under the invalid interface ID as defined in https://eips.ethereum.org/EIPS/eip-165[ERC-165].
This allows for later factory instances to override the original Service Proxy implementation is desired.
Because of this reserved interface ID, there is no need to declare the Service Proxy in a new Service Proxy configuration.