= Autonomous Service Engine Architecture
ifndef::compositing[]
:author: cyotee doge
:email: cyotee@syscoin.org
:revdate: 2022-02-19
:revnumber: 0.1
:revremark: Initial draft.
:toc:
:toclevels: 6
:sectnums:
:data-uri:
:stem: asciimath
:pathtoroot: ../../
:imagesdir: {pathtoroot}
:includeprefix: {pathtoroot}
:compositing:
endif::[]

The Autonomous Service Engine (ASE) is a proxy factory.
The architecture merges the Diamond Proxy and Factory design patterns.
Users may have the factory deploy a proxy configured with the functionality they wish.
This allows users to compose a variety of functionality in a single proxy.

include::{includeprefix}docs/architecture/design_patterns/daosys-design_patterns.adoc[leveloffset=+1]

== Architecture

The Autonomous Service Engine uses a on-chain factory to deploy minimal proxies of a customized Diamond Proxy that is configured with facets as defined by the user.
Because of the customization that deviates sharply from the Diamond standard as defined in https://eips.ethereum.org/EIPS/eip-2535[ERC-2535] the defining terms are changed.
Under the ASE framework, the customized Diamond proxies are termed Service Proxies.
The Facets defined in https://eips.ethereum.org/EIPS/eip-2535[ERC-2535] are termed Services.

The distinction is in two factors.
Delegate Service Proxies are immutable.
The functions defined in https://eips.ethereum.org/EIPS/eip-2535[ERC-2535] to reconfigure a proxy to use new facets is not available by default in a Service Proxy.
This is done because there is not acceptable solution to the risk updates present to users of the proxy.
A Service Proxy may be configured with a Service that exposes a https://eips.ethereum.org/EIPS/eip-2535[ERC-2535] compliant interface for private instances.
The ASE will only deploy reconfiguration Services for a Service Proxy that includes an explicit ACL Service.

Second, Service Proxies are wrapped in a Minimal Proxy as defined in https://eips.ethereum.org/EIPS/eip-1167[ERC-1167].
The Service Proxy logic is itself a Delegate Service.
The Service Proxy Factory uses https://eips.ethereum.org/EIPS/eip-1167[ERC-1167] to deploy a Minimal Proxy that directs to the Service Proxy logic.
This minimizes the transaction fee for deploying new proxies with a minimal increase in per-transaction fees for use.
This also allows easier verification that a new Service Proxy is reusing proven code.
Finally, for particularly sensitive Services, a circuit breaker can be included to protect all Service Proxies consuming that service.
For this reason, Services will implemented to be as minimal as possible.
With emergency withdrawal or liquidation services to gracefully degrade if a service is disabled.

image::images/architecture/daosys-architecture-01-ase-02-architecture.drawio.svg[align=center]

include::./components/daosys-components.adoc[leveloffset=+1]