= DAOSys Tokenomics
ifndef::compositing[]
:author: cyotee doge
:email: cyotee@syscoin.org
:revdate: 2022-02-19
:revnumber: 0.1
:revremark: Initial draft.
:toc:
:toclevels: 6
:sectnums:
:data-uri:
:stem:
:imagesdir: ../
:compositing:
endif::[]

== Problem Statement

Current DAO tokenomics are not suited to 

== Design Intent

The DAOSys tokenomics is based on securing and managing interest bearing market positions to ensure long term health of the targeted market.
This capital management is does using synthetic derivative tokens that directly index the capital allocation in the treasury and the target markets.
The indexing process is achieved by applying on-chain price oracles and rebasing to make the index synthetics accurately reflect the aspects of the markets being indexed.

The management of user deposits is executed similar to existing lending markets.
When a user deposits one of the supported assets, they are given an interest bearing continuously rebasing synthetic token, termed the Treasury Token (TT), that represents the interest due to the user.
The primary difference is the exchange rate for the TT will reflect the commitment of interest due to other users, and the time the vault will need to accrue interest from the deposit.
This makes the TT more akin to a bond instead of a typical liquidity pool token as on other platforms.
Additionally, the vault produces another interest bearing continuously rebasing synthetic token that represents the debt owed by the vault for capital allocated to one of the integrated markets, termed the Treasury Debt Token (TDT).

Unlike other platforms, the DAOSys lending platform will borrow any provided liquidity until other users borrows the capital.
This provides the initial index for rebasing the TDT that allows the vault to provide liquidity to pair with the deposited asset.
Any user may then buy the TDT, and trade it for the TT on the market where the vault has listed TT and TDT.
The emission of the expanded supply of the TT and TDT directly changes the balance of all holders, including the market liquidity through its rebase.
By only releasing TT and TDT into circulation by trading through the exchange liquidity, a hard price floor can be maintained.
Additionally, by rebasing the synthetics within the same transaction as deposits, a soft price floor can be supported to incentivize users to acquire tokens by interacting with the vault.
This allows the vault to take advantage of supply expansion of the TT and TDT to offer depositors a lower price then the market.

Because the TDT is distributed across several markets by being paired with the assets accepted for deposit, the manipulation of the price floor is proportional across all markets.
This weights the incentive towards assets that the vault has paid out to users as interest and wishes to recoup to meet the commitment for interest due to other holders.
The resulting market from several Constant Product Trading pools consisting of the TDT paired with the TT and the other assets the vault accepts for deposit links them through the rebase to form a kind of virtual weighted liquidity pool like Curve.
As users and the vault trade through these liquidity pools, the weighting changes to reflect the exit of capital.
This weighting results in a reduced price of the TDT for the asset that users have chosen to actualize the interest due to them.

== Vault Processes

=== Token Generation

DAOSys does not mint new tokens.
The minting process used by most liquidity pool implementations is not suited to achieving DAOSys' goals.
DAOSys manages it's tokens by rebasing based on user deposits.
The process of rebasing a token that indexes the vault liquidity allows DAOSys to handle deposits more like selling a bond.
DAOSys effectively borrows deposited assets to allocate them into markets on behalf of users to achieve an interest rate.
That interest rate, and the interest due to other users is represented in the rebasing process and the trading activity the vault executes.

Most liquidity pools behave as an impartial mediator between the provider and the market for which they are providing liquidity.
For lending liquidity pools, the lending platform is simply mediating the collateralization and debt process between lenders and debtors.
For exchange liquidity pools, the DEX is simply mediating the order book between liquidity providers and traders.
DAOSys fulfills it's design ethos of DAOs acting as algorithmic agents by acting as the borrower of last resort for lenders.

DAOSys generates new tokens to reflect an inflow of capital by rebasing it's tokens.
This rebase allows these tokens to index the state of the treasury.
This is done by tracking the deposit and borrowing of assets after pricing them in the native coin of the host blockchain.
This is accomplished by using two tokens that index different portions of the treasury.

The Treasury Token (TT) indexes the capital that has been deposited in the vault.
Each pool tracks it's contribution 


image::images/finance/daosys-finance-01-strategies-00-overview.drawio.svg[align=center]

=== Lending

==== Initialization

image::images/finance/daosys-finance-01-strategies-01-lending-01-single_asset-00-initialization.drawio.svg[align=center]

==== Single Asset Deposit

image::images/finance/daosys-finance-01-strategies-01-lending-01-single_asset-01-deposit.drawio.svg[align=center]

A lending market requires deposits of liquidity to enable borrowing.
In DAOSys this is handled through utilization based liquidity pools.
Typical utilization based liquidity pools provide users a liquidity pool token to represent their deposit and interest earned in that asset.
DAOSys aggregates all deposits into debt (TDT) and collateral (TT) tokens.

===== Process

* Step 1 - User initiates deposit of an accepted token.
** This diagram shows the process for two tokens, designated $T1 and $T2.

* Step 2 - Upon initiation of the deposit, the vault takes the designated token from the user.
The amount deposited is added to the total supply of assets deposited.
This is tracked similar to a rebasing token and designated as $TCT-T1 and $TCT-T2, but not accessible as a token with an independent address.
The supply of all TCT is aggregated into the TT.
The deposited TX causes the expansion of the respective TCT-TX and it's contribution to the expansion of the TT is immediately seen in all liquidity containing TT.
The aggregation process is documented in it's own section.

* Step 3 - The vault borrows all funds as the deposited to place in liquidity in the debt market with the TDT.
The vault does this with a virtual token similar to the $TCT-TX that is designated as TDT-T1 and TDT-T2.
All the TDT-TX is aggregated into the TDT.

* Step 4 - After borrowing the deposited TX the expansion of the respective TDT-TX and it's contribution to the expansion of the TDT is immediately seen in all liquidity containing TDT.
The vault uses the deposited TX to buy TDT from the liquidity of TDT paired with TX.

* Step 5 - After purchasing TDT with the deposited TX, the vault then trades the TDT for the TT.

==== LP Token Collateral Deposit for Leverage into Liquidity

image::images/finance/daosys-finance-01-strategies-01-lending-02-double_asset-01-lp_token_deposit_compounding.drawio.svg[align=center]

Following the basic investment strategy for the vault, interest bearing assets are accepted for direct deposit.
This process covers how liquidity pool tokens containing the T1 and T2 from the previous process as accepted for deposit.
The contents of the underlying assets is calculated and credited as a deposit of those underlying assets.
Because the contents are provided as collateral for leveraging assets from the respective debt markets the vault does not borrow these assets.
Also, because the vault already borrowed the underlying assets upon deposit, the leverage does not need to credit any further debt.

===== Process

Step 1 - When a user initiates a deposit of LP tokens the vault take the tokens.
Upon taking the LP tokens, the vault calculates the contents of the underlying assets.
These are credited as contributions to the respective TCT-TX, causing a rebase in those virtual tokens and aggregation into the TT through a further rebase.

Step 2 - The vault matches the deposit of collateral in the form of LP tokens by withdrawing liquidity from the debt market.
The T1 and T2 of withdrawn from the debt market is deposited in market liquidity for both of those assets.

Step 3 - The TDT withdrawn from the debt market is then sold to buy TT to give to the user for their deposit.

==== LP Token Liquidation Deposit

image::images/finance/daosys-finance-01-strategies-01-lending-02-double_asset-02-lp_token_deposit_liquidation.drawio.svg[align=center]

Following the ethos of self-sovereignty a user may also liquidate LP tokens to deposit into the treasury.
The extraction of capital does violate the basic investment strategy of securing assets into interest bearing positions.
But this considered a net gain by obtaining the assets to meet the interest due to depositors.
This also provides the liquidity for depositors to reallocate to market liquidity.
The process of accepting LP tokens to be liquidated for deposit is the same as accepting the underlying assets as separate deposits.
The benefit to users of depositing in this manner is that they can take advantage of the supply expansions across several markets.

===== Process

* Step 1 - The user initiates deposit of LP tokens to have the vault take the tokens.

* Step 2 - The vault withdraws the underlying assets in that liquidity.
the extracted capital is then processed as a deposit of each asset in the single asset lending liquidity pools.

* Step 3 - After each deposit is processed and converted to TDT, the proceeds are combined to trade for the TT.

=== Treasury Management

The consolidation of all deposits into the TT provides holders a means to control the allocation of their share of liquidity.
By staking their TT to bond with a allocation of capital, users may control how their share of the treasury is managed.
The processes that allow users to reallocate their share of the liquidity by bonding their TT ensures the health of the managed investments.
This allows the market to discover the balance of capital extraction versus long term health, favoring market longevity.

==== Liquidity Provision

image::images/finance/daosys-finance-01-strategies-01-lending-02-double_asset-07-tt_liquidity_compounding.drawio.svg[align=center]

A holder of TT may allocate their share of the liquidity to providing liquidity for a particular market.
To protect the target market, the holder must bond their TT against the future interest from the liquidity provision.
If an immediate arbitrage opportunity becomes available that is the amount of interest the market can support for providing liquidity.

===== Process

* Step 1 - The holder of TT initiates the bonding process and the vault takes the TT from the user.
The value of the deposited TT is calculated to the two assets in the target market through the TDT liquidity for each asset.
The the matching value is withdrawn from the TDT liquidity at the price ratio of the target market.

* Step 2 - The withdrawn liquidity of each asset is deposited in the target market.
The LP tokens that result from the deposit is credited to the user along with the staked TT under a NFT based vault.
This bonds the TT to the LP tokens to secure the capital allocation against the future interest of the provided liquidity.

* Step 3 - The withdrawn TDT is combined and used to buy TT from the market.
This purchased TT is deposited in the NFT vault as an immediate interest payment for reallocating capital within the treasury.
From here the holder of this NFT vault may withdraw TT above the value of the bonded LP tokens.
The bonded LP tokens are not available for any public liquidation process.

==== Bond Liquidation

image::images/finance/daosys-finance-01-strategies-01-lending-02-double_asset-08-tt_liquidity_liquidation.drawio.svg[align=center]

Once a holder has bonded their TT with LP tokens, they may liquidate those LP tokens to force an early maturation.
The liquidation is processed as a withdrawal of those assets from lending liquidity, and a repayment of debt of that asset.
The process is similar to the deposit of those assets, but the supply of the respective TCT-TX and TDT-TX is contracted.
The result is a contraction the supplies of TT and TDT.
This means that the liquidation is processed by trading through the now contracted liquidity, resulting in a steeper price curve.
This acts as the counter balance to the expansion in supply and shallowing of the price curve provided to incentivize deposits.
The difference between these price curves at any given point is the effective interest due to the user that staked their TT.

===== Process

* Step 1 - The holder of a NFT vault initiates the liquidation of some or all of their bonded LP tokens.
The liquidity is withdrawn from the target market.

* Step 2 - The assets withdrawn from market liquidity while under bond are used to repay the debt owed to current holders.
This is done by processing a repayment through the lending liquidity pools for those assets.
The repayment is completed by rebasing the respective TCT-TX and TDT-TX to contract their supply by the same factor as the supply expansion for deposit.
A difference between the expansion and contraction rates can be introduced as an effective tax or subsidy.

* Step 3 - After contracting the supplies of TDT and TT the withdrawn assets are traded for TDT in the debt markets underlying the lending liquidity.
The supply contraction and the proportional impact on the debt market liquidity steepens the price curve to ensure that market can support the extraction of capital.

* Step 4 - The TDT proceeds from the sale are then consolidated and sold for TT.
The proceeds of TT are deposited in the NFT vault for the user.
This allows the holders to hasten the maturation of their bond by releasing the claimed liquidity.